name: Build container

on:
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: x86_64
            target: x86_64-unknown-linux-gnu
          - platform: aarch64
            target: aarch64-unknown-linux-gnu
          - platform: armv7
            target: armv7-unknown-linux-gnueabihf
    name: Build for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Cross
        run: |
          curl -SsL https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cross
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build the binary
        run: RUSTFLAGS="-C target-feature=+crt-static" ~/.cargo/bin/cross build --profile release-lto --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.platform }}
          path: target/${{ matrix.target }}/release-lto/redirect-rs

  push:
    name: Push image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Download artifacts
        uses: actions/download-artifact@v5
      - name: Set executable permissions
        run: |
          chmod +x */redirect-rs
      - name: Push the image
        run: |
          docker run -v $(pwd):/srv darktohka/ocitool upload --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
